// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKcttWRVatzNO_KMJ2sOF4wPAPyTMdUww',
    appId: '1:703455849443:web:8faae2e758790bedf7ced6',
    messagingSenderId: '703455849443',
    projectId: 'chat-app-5ec7b',
    authDomain: 'chat-app-5ec7b.firebaseapp.com',
    storageBucket: 'chat-app-5ec7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD9OCVTlueu2W5ZQdrNA5QqkdOGkVhzyQ',
    appId: '1:703455849443:android:8889b89a9b9b7551f7ced6',
    messagingSenderId: '703455849443',
    projectId: 'chat-app-5ec7b',
    storageBucket: 'chat-app-5ec7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHpHlJ86YQm5K3GX6Gjo47-z9KP_GDYME',
    appId: '1:703455849443:ios:6683cb7abd0dfc13f7ced6',
    messagingSenderId: '703455849443',
    projectId: 'chat-app-5ec7b',
    storageBucket: 'chat-app-5ec7b.appspot.com',
    iosBundleId: 'com.example.chat.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHpHlJ86YQm5K3GX6Gjo47-z9KP_GDYME',
    appId: '1:703455849443:ios:6683cb7abd0dfc13f7ced6',
    messagingSenderId: '703455849443',
    projectId: 'chat-app-5ec7b',
    storageBucket: 'chat-app-5ec7b.appspot.com',
    iosBundleId: 'com.example.chat.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKcttWRVatzNO_KMJ2sOF4wPAPyTMdUww',
    appId: '1:703455849443:web:5d7f795949430ed6f7ced6',
    messagingSenderId: '703455849443',
    projectId: 'chat-app-5ec7b',
    authDomain: 'chat-app-5ec7b.firebaseapp.com',
    storageBucket: 'chat-app-5ec7b.appspot.com',
  );
}
